# Generated by Django 3.0.2 on 2020-01-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200108_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
