# Generated by Django 3.0.2 on 2020-01-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_publication_image_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dewey',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='dewey',
            name='bg_color',
            field=models.CharField(default='*', max_length=7),
        ),
        migrations.AddField(
            model_name='dewey',
            name='text_color',
            field=models.CharField(default='*', max_length=7),
        ),
        migrations.AlterField(
            model_name='publication',
            name='isbn',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
